
#ifndef BEHAVIORAL_CHAIN_OF_RESPONSIBILITY_RESPONSE_CODE_HPP
#define BEHAVIORAL_CHAIN_OF_RESPONSIBILITY_RESPONSE_CODE_HPP

enum class ResponseCode{
	SUCCESS = 0,
	BAD_LOGIN = 1,
	BAD_PASSWORD = 2
};

#endif // BEHAVIORAL_CHAIN_OF_RESPONSIBILITY_RESPONSE_CODE_HPP