
cc_test(
	name = "test_prototype",
	srcs = [
		"test_prototype.cpp"
	],
	deps = [
		"//creational/prototype:prototype_library",
		"@googletest//:gtest",
		"@googletest//:gtest_main"
   ]
)

cc_library(
	name = "prototype_library",
	hdrs = [
		"prototype_pizza.hpp",
		"diavola.hpp",
		"vege.hpp",
		"undefined_pizza.hpp",
		"waiter.hpp",
		"client.hpp"
	]
)
