
cc_test(
	name = "test_prototype",
	srcs = [
		"test_prototype.cpp"
	],
	deps = [
		"//creational/prototype:simple_prototype_classes",
		"@googletest//:gtest",
		"@googletest//:gtest_main"
   ]
)

cc_library(
	name = "simple_prototype_classes",
	hdrs = [
		"test_prototype.hpp"
	]
)
