cc_test(
	name = "test_singleton",
	srcs = [
		"test_singleton.cpp"
	],
	deps = [
		"//creational:singleton",
       "@googletest//:gtest",
       "@googletest//:gtest_main",
   ],
)

cc_library(
	name = "singleton",
	hdrs = [
		"singleton.hpp"
	],
	srcs = [
		"singleton.cpp"
	]
)